language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ngochieu276/docker-react  -f Dockerfile.dev .

script:
  - docker run -e CI=true ngochieu276/docker-react npm run test 